FROM python:3.12-slim

# Variables de entorno para Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Directorio de trabajo
WORKDIR /app

# Instalamos dependencias del sistema (necesarias para psycopg2)
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiamos e instalamos dependencias
COPY requierements_def.txt .
RUN pip install --no-cache-dir -r requierements_def.txt

# Copiamos el código
COPY . .

# Exponemos el puerto
EXPOSE 8000

# Comando para iniciar FastAPI (NOTA: "asis" es tu variable de FastAPI)
CMD ["uvicorn", "main:asis", "--host", "0.0.0.0", "--port", "8000", "--reload"]